In [1]:
import pandas as pd
tmdb = pd.read_csv('data/tmdb_1.csv')

div = pd.read_csv('data/oscars_diversity.csv')

streaming = pd.read_csv('data/streaming.csv')

imdb = pd.read_csv('data/imdb_ratings.csv')

rt = pd.read_csv('data/rotten_tomatoes.csv')

In [2]:
tmdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 152686 entries, 0 to 152685
Data columns (total 24 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    152686 non-null  int64
 1   title                 152686 non-null  str
 2   vote_average          152686 non-null  float64
 3   vote_count            152686 non-null  int64
 4   status                152686 non-null  str
 5   release_date          152395 non-null  str
 6   revenue               152686 non-null  int64
 7   runtime               152686 non-null  int64
 8   adult                 152686 non-null  bool
 9   backdrop_path         110880 non-null  str
 10  budget                152685 non-null  float64
 11  homepage              26012 non-null   str
 12  imdb_id               148977 non-null  str
 13  original_language     152685 non-null  str
 14  original_title        152685 non-null  str
 15  overview              147479 non-null  str
 16  popularity            152685 non-null  float64
 17  poster_path           146770 non-null  str
 18  tagline               51184 non-null   str
 19  genres                145155 non-null  str
 20  production_companies  119233 non-null  str
 21  production_countries  136714 non-null  str
 22  spoken_languages      142036 non-null  str
 23  keywords              91288 non-null   str
dtypes: bool(1), float64(3), int64(4), str(16)
memory usage: 26.9 MB

In [3]:
tmdb.head()

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [4]:
streaming.info()

<class 'pandas.DataFrame'>
RangeIndex: 5047 entries, 0 to 5046
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         5047 non-null   str
 1   title                      5047 non-null   str
 2   year                       5047 non-null   int64
 3   type                       5047 non-null   str
 4   num_subscription_services  5047 non-null   int64
 5   has_subscription           5047 non-null   bool
 6   exclusive                  5047 non-null   bool
 7   rent_buy_only              5047 non-null   bool
 8   cinema_only                5047 non-null   bool
 9   subscription_services      3978 non-null   str
 10  monetization_types         4710 non-null   str
dtypes: bool(4), int64(2), str(5)
memory usage: 295.9 KB

In [5]:
streaming.head()

,id,title,year,type,num_subscription_services,has_subscription,exclusive,rent_buy_only,cinema_only,subscription_services,monetization_types
0,tm1598352,Send Help,2026,movie,2,True,False,False,False,Disney+|Hulu,BUY|CINEMA|FLATRATE|RENT
1,tm1602729,"Good Luck, Have Fun, Don't Die",2026,movie,0,False,False,False,False,NaN,BUY|CINEMA|RENT
2,tm1457585,The Super Mario Galaxy Movie,2026,movie,0,False,False,False,False,NaN,BUY|CINEMA|RENT
3,tm1520393,Hoppers,2026,movie,1,True,True,False,False,Disney+,BUY|CINEMA|FLATRATE|RENT
4,tm1610095,The Sheep Detectives,2026,movie,0,False,False,False,False,NaN,BUY|CINEMA

In [6]:
div.info()

<class 'pandas.DataFrame'>
RangeIndex: 10396 entries, 0 to 10395
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year_film      10396 non-null  int64
 1   year_ceremony  10396 non-null  int64
 2   ceremony       10396 non-null  int64
 3   Category       10396 non-null  str
 4   gender         10396 non-null  str
 5   name           10395 non-null  str
 6   Race           10396 non-null  str
 7   film           10092 non-null  str
 8   winner         10396 non-null  bool
dtypes: bool(1), int64(3), str(5)
memory usage: 660.0 KB

In [7]:
div.head()

,year_film,year_ceremony,ceremony,Category,gender,name,Race,film,winner
0,1927,1928,1,Best Actor,Male,Emil Jannings,White,The Last Command,True
1,1927,1928,1,Best Actress,Female,Janet Gaynor,White,7th Heaven,True
2,1928,1929,2,Best Actor,Male,Warner Baxter,White,In Old Arizona,True
3,1928,1929,2,Best Actress,Female,Mary Pickford,White,Coquette,True
4,1929,1930,3,Best Actor,Male,George Arliss,White,Disraeli,True

In [8]:
imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 1726786 entries, 0 to 1726785
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0    tconst        str
 1   averageRating  float64
 2   numVotes       int64
dtypes: float64(1), int64(1), str(1)
memory usage: 39.5 MB

In [9]:
imdb.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2237
1  tt0000002            5.4       327
2  tt0000003            6.4      2401
3  tt0000004            5.0       203
4  tt0000005            6.2      3105

In [10]:
rt.info()

<class 'pandas.DataFrame'>
RangeIndex: 12413 entries, 0 to 12412
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           12413 non-null  str
 1   url             12413 non-null  str
 2   release_date    12400 non-null  str
 3   critic_score    9377 non-null   str
 4   audience_score  10826 non-null  str
dtypes: str(5)
memory usage: 485.0 KB

In [11]:
rt.head()

,title,url,release_date,critic_score,audience_score
0,Love Story,https://www.rottentomatoes.com/m/love_story,"Released Dec 16, 1970",63%,75%
1,Airport,https://www.rottentomatoes.com/m/airport,"Released Apr 5, 1970",75%,54%
2,M*A*S*H,https://www.rottentomatoes.com/m/mash,"Released Jan 30, 1970",84%,83%
3,Patton,https://www.rottentomatoes.com/m/patton,"Released Jan 25, 1970",91%,93%
4,The Aristocats,https://www.rottentomatoes.com/m/the_aristocats,1970,NaN,NaN